# Generated by Django 5.0.1 on 2024-01-31 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_sum",
            new_name="summary_cost",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="count",
        ),
        migrations.CreateModel(
            name="Products_in_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_amount", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homework_app.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homework_app.product",
                    ),
                ),
            ],
        ),
    ]
