# Generated by Django 5.0.1 on 2024-01-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework_app", "0002_rename_order_sum_order_summary_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
