# Generated by Django 5.0.1 on 2024-01-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework_app", "0003_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
