# Generated by Django 5.0.1 on 2024-01-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework_app", "0004_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="summary_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
