# Generated by Django 5.0.1 on 2024-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework_app", "0005_alter_order_summary_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(to="homework_app.product"),
        ),
    ]
